/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDataRouteImport } from './routes/admin/data'
import { Route as AuthenticatedMypageRouteImport } from './routes/_authenticated/mypage'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPortfolioValuationRouteImport } from './routes/_authenticated/portfolio.valuation'
import { Route as AuthenticatedPortfolioAssetsRouteImport } from './routes/_authenticated/portfolio.assets'
import { Route as AuthenticatedPortfolioAssetsIdRouteImport } from './routes/_authenticated/portfolio.assets.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMypageRoute = AuthenticatedMypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortfolioValuationRoute =
  AuthenticatedPortfolioValuationRouteImport.update({
    id: '/portfolio/valuation',
    path: '/portfolio/valuation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortfolioAssetsRoute =
  AuthenticatedPortfolioAssetsRouteImport.update({
    id: '/portfolio/assets',
    path: '/portfolio/assets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortfolioAssetsIdRoute =
  AuthenticatedPortfolioAssetsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortfolioAssetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mypage': typeof AuthenticatedMypageRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/portfolio/assets': typeof AuthenticatedPortfolioAssetsRouteWithChildren
  '/portfolio/valuation': typeof AuthenticatedPortfolioValuationRoute
  '/portfolio/assets/$id': typeof AuthenticatedPortfolioAssetsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mypage': typeof AuthenticatedMypageRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/portfolio/assets': typeof AuthenticatedPortfolioAssetsRouteWithChildren
  '/portfolio/valuation': typeof AuthenticatedPortfolioValuationRoute
  '/portfolio/assets/$id': typeof AuthenticatedPortfolioAssetsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mypage': typeof AuthenticatedMypageRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/portfolio/assets': typeof AuthenticatedPortfolioAssetsRouteWithChildren
  '/_authenticated/portfolio/valuation': typeof AuthenticatedPortfolioValuationRoute
  '/_authenticated/portfolio/assets/$id': typeof AuthenticatedPortfolioAssetsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/mypage'
    | '/admin/data'
    | '/admin/login'
    | '/admin/users'
    | '/admin/'
    | '/portfolio/assets'
    | '/portfolio/valuation'
    | '/portfolio/assets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/mypage'
    | '/admin/data'
    | '/admin/login'
    | '/admin/users'
    | '/admin'
    | '/portfolio/assets'
    | '/portfolio/valuation'
    | '/portfolio/assets/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/mypage'
    | '/admin/data'
    | '/admin/login'
    | '/admin/users'
    | '/admin/'
    | '/_authenticated/portfolio/assets'
    | '/_authenticated/portfolio/valuation'
    | '/_authenticated/portfolio/assets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mypage': {
      id: '/_authenticated/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof AuthenticatedMypageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio/valuation': {
      id: '/_authenticated/portfolio/valuation'
      path: '/portfolio/valuation'
      fullPath: '/portfolio/valuation'
      preLoaderRoute: typeof AuthenticatedPortfolioValuationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio/assets': {
      id: '/_authenticated/portfolio/assets'
      path: '/portfolio/assets'
      fullPath: '/portfolio/assets'
      preLoaderRoute: typeof AuthenticatedPortfolioAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio/assets/$id': {
      id: '/_authenticated/portfolio/assets/$id'
      path: '/$id'
      fullPath: '/portfolio/assets/$id'
      preLoaderRoute: typeof AuthenticatedPortfolioAssetsIdRouteImport
      parentRoute: typeof AuthenticatedPortfolioAssetsRoute
    }
  }
}

interface AuthenticatedPortfolioAssetsRouteChildren {
  AuthenticatedPortfolioAssetsIdRoute: typeof AuthenticatedPortfolioAssetsIdRoute
}

const AuthenticatedPortfolioAssetsRouteChildren: AuthenticatedPortfolioAssetsRouteChildren =
  {
    AuthenticatedPortfolioAssetsIdRoute: AuthenticatedPortfolioAssetsIdRoute,
  }

const AuthenticatedPortfolioAssetsRouteWithChildren =
  AuthenticatedPortfolioAssetsRoute._addFileChildren(
    AuthenticatedPortfolioAssetsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMypageRoute: typeof AuthenticatedMypageRoute
  AuthenticatedPortfolioAssetsRoute: typeof AuthenticatedPortfolioAssetsRouteWithChildren
  AuthenticatedPortfolioValuationRoute: typeof AuthenticatedPortfolioValuationRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMypageRoute: AuthenticatedMypageRoute,
  AuthenticatedPortfolioAssetsRoute:
    AuthenticatedPortfolioAssetsRouteWithChildren,
  AuthenticatedPortfolioValuationRoute: AuthenticatedPortfolioValuationRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminDataRoute: AdminDataRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
